### ISSUE TITLE
Why not use the standard com.android.volley package ?

### ISSUE THREAD

**Issue by martinbonnin** [mopub/mopub-android-sdk#140]
Instead of com.mopub.volley. This would allow to share the volley implementation with other parts of the app.

**Comment by NassarS** [comment]
Hi Martin,

Good question, and one that we debated.

If Volley were available via a standard repository like Maven Central, we
would probably require people to create their own dependency. Since it's
not, it's actually somewhat problematic to ask developers to include it,
especially since we require a version of Volley newer than this change
<https://android.googlesource.com/platform/frameworks/volley/+/3b05ab343f2e9deba7c196f30e41d363e3458b20>,
and it isn't easy to express that requirement via standard dependency
resolution in Gradle. Packaging it internally seemed like a more fail-safe
solution.

Thankfully, Volley is pretty small.

Nassar

**Comment by martinbonnin** [comment]
Ok thanks. Any idea why volley is not on maven ? Maybe we can push them to do so...


Le 5 février 2015 18:01:24 GMT+01:00, Nassar Stoertz <notifications@github.com> a écrit :
>Hi Martin,
>
>Good question, and one that we debated.
>
>If Volley were available via a standard repository like Maven Central,
>we
>would probably require people to create their own dependency. Since
>it's
>not, it's actually somewhat problematic to ask developers to include
>it,
>especially since we require a version of Volley newer than this change
><https://android.googlesource.com/platform/frameworks/volley/+/3b05ab343f2e9deba7c196f30e41d363e3458b20>,
>and it isn't easy to express that requirement via standard dependency
>resolution in Gradle. Packaging it internally seemed like a more
>fail-safe
>solution.
>
>Thankfully, Volley is pretty small.
>
>Nassar
>
>
>On Thu, Feb 5, 2015 at 1:53 AM, Martin Bonnin
><notifications@github.com>
>wrote:
>
>> Instead of com.mopub.volley. This would allow to share the volley
>> implementation with other parts of the app.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mopub/mopub-android-sdk/issues/140>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mopub/mopub-android-sdk/issues/140#issuecomment-73083321

-- 
Martin
