### ISSUE TITLE
3.5.0 to maven repo

### ISSUE THREAD

**Issue by jhansche** [mopub/mopub-android-sdk#151]
The Fabric version (with Kit support) is not yet available on maven.  3.4.0 took almost a whole month before it was available.  Would prefer to get this 3.5.0 update sooner than that, as it fixes one of our highest volume crashes from the 3.4.0 release.

https://twittersdk.artifactoryonline.com/twittersdk/repo/com/mopub/sdk/android/mopub/

**Comment by joeblubaugh** [comment]
Hi Joe,

The version of MoPub hosted at 'https://maven.fabric.io/public' is really intended for use with Fabric. This is a non-open source version of MoPub that includes some non-public changes from the version hosted here on Github. Fabric has its own test and release process, which is why there is usually some delay between MoPub releases and version updates in Fabric.

If you require the newest version of MoPub I'd recommend building the SDK from source and installing it in your local Maven repo. We include a set of POM files with the source that should make this straightforward:
```
$ cd mopub-sdk; mvn clean install -DskipTests
```
[Full Maven Instructions here](https://github.com/mopub/mopub-android-sdk/wiki/Getting-Started#maven-integration)

**Comment by jhansche** [comment]
@joeblubaugh 
We do use the Kit with Fabric, and that is how the integration is described at https://fabric.io/downloads/gradle.  The added benefit, as you mentioned, is that it's readily available in a maven repository without requiring manual building and deployment.  We use Fabric to integrate Crashlytics (with Beta and Answers) and MoPub.

We do use Nexus to host and proxy maven artifacts, so it wouldn't be a big deal to deploy the artifact manually.  But then what's the reason to use Fabric at all, if it's so out of sync?

**Comment by joeblubaugh** [comment]
We're definitely working to reduce the delay between releases - thanks for the feedback.

**Comment by jhansche** [comment]
@joeblubaugh, I see that 3.5.0 finally made it into the maven repo, but I still don't see 3.6.0 or 3.6.1.

Is there any reason not to deploy the open source version to the maven repo at time of tag & release?  And then the Fabric+Kit version could be deployed as a new artifact, whenever the Fabric team gets around to integrating and testing the newest version and implements the Fabric Kit for it.

I may just start doing that myself, since there's a pretty significant lag every time new versions are released.  What else goes into the Fabric version of the artifact that is different from the open source version?  Is it just the MoPub class extending Kit?  What else would we lose by building the open source version instead of waiting for the Fabric team to publish it to maven?
