### ISSUE TITLE
Is MoPub caching ads before loading them? 

### ISSUE THREAD

**Issue by KrutiMevada** [mopub/mopub-android-sdk#159]
Hi MoPub team,

Hope you are having great Monday.

I have an requirement in which videos are required to start playing as soon as the ad is loaded. Does mopub has any method by which i can specify cache ads in background so as soon as my activity is loaded the ads start playin video ?

Regards,
Kruti

**Comment by steffanc** [comment]
Hi Kruti,

The MoPub SDK actually caches VAST videos in a disk cache but the ad request (MoPubInterstitial) itself unfortunately can't be shared between activities since it holds onto an Activity object. Sharing it would cause a memory leak.

This means that the first time you play the video, it will have to completely download the payload over the network, but each time after that it should resolve quickly since it will be cached on disk, assuming it hasn't been ejected.
