### ISSUE TITLE
impression tracking doesn't work for MoPubCustomEventNative ads used outside adapters

### ISSUE THREAD

**Issue by nemdub** [mopub/mopub-android-sdk#174]
We have a native ad creative defined in the MoPub web interface, which results in a MoPubCustomEventNative being delivered to our Android app. We're not using any kind of adapters (MoPubStreamAdPlacer, NativeAdViewHelper) in this case, as this is a fullscreen native ad.
This kind of ad doesn't show any impressions in our reports for the Android version of the app (on iOS it works fine), so we started investigating why that is the case..

My assumption why it doesn't work is the following:
in the iOS SDK, calling prepareForDisplayInView: on MPNativeAd sets up impression tracking, while on Android, calling prepare(View v) on NativeResponse only sets up click tracking

currently, our code looks something like this:

```
ViewBinder viewBinder = new ViewBinder.Builder(R.layout.commercials_activity_layout) ... .build();
final MoPubNativeAdRenderer adRenderer = new MoPubNativeAdRenderer(viewBinder);
RequestParameters requestParameters = new RequestParameters.Builder()
    .location(location)
    .keywords(keywords)
    .desiredAssets(desiredAssets)
    .build();

final MoPubNative moPubNative = new MoPubNative(this, mAdUid, new MoPubNative.MoPubNativeNetworkListener() {
    @Override
    public void onNativeLoad(final NativeResponse nativeResponse) {
        nativeResponse.prepare(mContentContainer);
        adRenderer.renderAdView(mContentContainer, nativeResponse);
    }

    @Override
    public void onNativeFail(NativeErrorCode errorCode) {
    }
});
moPubNative.makeRequest(requestParameters);
```

Is there anything that we're missing?
I don't think we should be calling `nativeResponse.recordImpression(mContentContainer)` manually.

Thanks

**Comment by edwardho** [comment]
Hello nemdub,

What SDK version are you using? What is your MoPub alias? What is the app name/ad unit you are seeing this issue under? Please email support@mopub.com with the context and this issue linked.

Please make sure that MoPubNativeListener moPubNativeListener is not null as it provides the callbacks for MoPubNativeListener#onNativeImpression(...).

Looking at your code, you seem to be passing MoPubNativeNetworkListener instead of moPubNativeListener. This would cause impressions and clicks not to be tracked.

https://github.com/mopub/mopub-android-sdk/wiki/Legacy-Native-Ads-Integration

Please note that the MoPub Github Issue Reporting Section will now be housed directly on the Twitter Developer Community Forum as this Issue Reporting Section will be closed on June 30th.

Please visit https://twittercommunity.com/c/fabric/mopub for any additional support questions or feel free to email support@mopub.com for further support regarding this issue.

Thank you for your patience and understanding.

Edward
