### ISSUE TITLE
onInterstitialFailed not triggered after failed load attempts

### ISSUE THREAD

**Issue by zawasp** [mopub/mopub-android-sdk#176]
Here are some logs:

07-01 15:53:24.999  24057-24057/? W/Ads﹕ Failed to load ad: 3
07-01 15:53:24.999  24057-24057/? D/MoPub﹕ Google Play Services interstitial ad failed to load.
07-01 15:53:24.999  24057-24057/? V/MoPub﹕ MoPubErrorCode: Third-party network failed to provide an ad.
07-01 15:53:24.999  24057-24057/? D/MoPub﹕ Loading failover url: - URL REMOVED
07-01 15:53:24.999  24057-24057/? D/MoPub﹕ Loading url: URL REMOVED
07-01 15:53:25.345  24057-24191/? D/MoPub﹕ Failed to retrieve GPS location: access appears to be disabled.
07-01 15:53:25.346  24057-24191/? D/MoPub﹕ Failed to retrieve network location: access appears to be disabled.
07-01 15:53:25.352  24057-24057/? I/MoPub﹕ Performing custom event.
07-01 15:53:25.352  24057-24057/? I/com.mopub﹕ Performing custom event.
07-01 15:53:25.352  24057-24057/? I/MoPub﹕ Failed to create custom event.
07-01 15:53:25.352  24057-24057/? I/com.mopub﹕ Failed to create custom event.

After this, our app stops, since it's waiting for either onInterstitialFailed or onInterstitialLoaded. These are not triggered. It seems `fromAdResponse` in AdLoader.java returns null in some cases.

**Comment by zawasp** [comment]
Perhaps here is the problem:
>AdLoader adLoader = AdLoader.fromAdResponse(mAdResponse, this);
>if (adLoader != null) { **<- this is null in my case ("Failed to create custom event" trace)**
>adLoader.load();
>}
>**//else should probably call moPubView.adFailed(errorCode);?**
>scheduleRefreshTimerIfEnabled();

**Comment by edwardho** [comment]
Hello Mircea,

It may be the case that it's not failing over gracefully because adLoader is null.

Can you please write into support@mopub.com with your case here linked and the verbose log cat logs, so we can see exactly what's happening? This will allow us to troubleshoot the issue and find a resolution.

Please note that the MoPub Github Issue Reporting Section will now be housed directly on the Twitter Developer Community Forum as this Issue Reporting Section will be closed on June 30th.

Please visit https://twittercommunity.com/c/fabric/mopub for any additional support questions or feel free to email support@mopub.com.

Thank you for your patience and understanding.

Edward
