### ISSUE TITLE
Documentation for native ads wrong?

### ISSUE THREAD

**Issue by robertdo** [mopub/mopub-android-sdk#305]
The documentation for native ads states "IMPORTANT: Do not set the background property on your ImageViews to null in order to handle PNG transparency gracefully as shown"
https://developers.mopub.com/docs/android/native/#step-1-set-up-your-native-ad-layout

However, the opposite is done in the sample code here:
https://github.com/mopub/mopub-android-sdk/blob/master/mopub-sample/res/layout/native_ad_list_item.xml#L19

So is documentation wrong, and you SHOULD set the background to @null?

**Comment by chauduyphanvu1** [comment]
@robertdo, this is not strictly enforced (meaning it's a best practice only - either approach does not break your implementation). The sample app uses a null background because there's no other view behind the ImageViews. Depending on your use case and ad layout, you can feel free to following the approach that most suits it.

Let us know if there are any questions,
Vu Chau
MoPub SDK Team
