### ISSUE TITLE
Issue Initializing BaseAdpterConfiguration Subclass  

### ISSUE THREAD

**Issue by im-ade** [mopub/mopub-android-sdk#310]
One line summary of the issue here:

BaseAdapterConfiguration's initializeNetwork method always fails because Context is not an instance of Activity.

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.6.0
#### Android Studio Version:
3.0.2
#### Device model and OS Version:
7.1.1
#### Steps to reproduce the behavior:

Following the steps located here https://developers.mopub.com/publishers/android/initialize/ on initializing custom ad networks I have created subclass of 
BaseAdapterConfiguration and successfully built the program.

#### Expected behavior:
The expected behavior is for my subclass of BaseAdapterConfiguration's initializeNetwork method to be called with a Context that is an instance of Activity so that I can initialize the networks SDK.

Method signature is

```
initializeNetwork(@NonNull Context context, @Nullable Map<String, String> configuration, @NonNull OnNetworkInitializationFinishedListener listener) 
```

#### Observed behavior:

Based on these two lines from the AdapterConfigurationManager class

https://github.com/mopub/mopub-android-sdk/blob/bb5a8c1f5a004c616c831345ba8f9913dadb5440/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/common/AdapterConfigurationManager.java#L58

https://github.com/mopub/mopub-android-sdk/blob/bb5a8c1f5a004c616c831345ba8f9913dadb5440/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/common/AdapterConfigurationManager.java#L256

The context passed will always be ApplicationContext and not an instance of Activity.

Is this the expected behavior? If so and the network's SDK requires a Context that is an instance of Activity to initialize then what is the recommended step/pattern to reattempt initialization after BaseAdapterConfiguration subclass's initializeNetwork call fails?

Thanks

**Comment by chauduyphanvu1** [comment]
@im-ade - you are correct that in this case, the `Context` is required to be an `Application Context`. If the custom event cannot initialize the network SDK because the SDK requires an `Activity Context`, initialization will be skipped. 

Is initialization for that network SDK required? Does the network SDK have another method to initialize using an Application Context? If not, is there another indirect way of initializing the SDK (such as by allocating a new, temporary, ad object or sending an ad request)?

Vu Chau
MoPub SDK Team

**Comment by im-ade** [comment]
@chauduyphanvu1 The network for the SDK needs to initialize using an activity as a parameter. I will look into indirectly initializing it but it doesn't seem like a practical approach. Not only does the network I am using  require initializing but a few of your supported mediation partners also do to:

https://github.com/mopub/mopub-android-mediation/blob/778cd4a4839b248a1f03e519d542ba4b3801b219/IronSource/src/main/java/com/mopub/mobileads/IronSourceAdapterConfiguration.java#L65

https://github.com/mopub/mopub-android-mediation/blob/778cd4a4839b248a1f03e519d542ba4b3801b219/OnebyAOL/src/main/java/com/mopub/mobileads/MillennialAdapterConfiguration.java#L55

https://github.com/mopub/mopub-android-mediation/blob/27b67acde58d72c595bc6178ce1ff2aade97ad01/UnityAds/src/main/java/com/mopub/mobileads/UnityAdsAdapterConfiguration.java#L60

These 3 mediation partners require an activity and will always skip initialization because an activity is never passed to it. 

In the case of using all 3 of these networks or even more (custom included) is the recommendation to initialize Mopub then initialize all of these networks separately in an indirect way?

**Comment by chauduyphanvu1** [comment]
@im-ade, we do have a few network SDKs that need an `Activity Context` (the ones you mentioned). Their initialization at the time of MoPub's initialization is currently being skipped due to different `Context` expectations.

However, network SDKs have a chance to do a lazy initialization at the time of the ad request. For example, ironSource can initialize its SDK [here](https://github.com/mopub/mopub-android-mediation/blob/778cd4a4839b248a1f03e519d542ba4b3801b219/IronSource/src/main/java/com/mopub/mobileads/IronSourceInterstitial.java#L109) because the `Context` passed to `IronSourceInterstitial. loadInterstitial()` is an [Activity Context](https://github.com/mopub/mopub-android-sdk/blob/dc46332d8fdf6c4ed99d588dd6776821b671a652/mopub-sdk/mopub-sdk-interstitial/src/main/java/com/mopub/mobileads/CustomEventInterstitialAdapter.java#L54), which ironSource needs to initialize.

Similarly, if your network SDK can initialize in the individual (interstitial, rewarded video, etc.) custom event, that'd be the second best approach.

**Comment by im-ade** [comment]
@chauduyphanvu1 we will go the lazy init approach for the SDKs that require Activity Context.

Thanks
