### ISSUE TITLE
Caused by java.lang.IllegalArgumentException Illegal argument.

### ISSUE THREAD

**Issue by circularity** [mopub/mopub-android-sdk#383]
com.mopub.common.Preconditions.checkArgumentInternal (Preconditions.java:248)
com.mopub.common.Preconditions.checkArgument (Preconditions.java:36)
com.mopub.network.AdLoader.<init> (AdLoader.java:75)
com.mopub.mobileads.AdLoaderRewardedVideo.<init> (AdLoaderRewardedVideo.java:30)
com.mopub.mobileads.RewardedAdsLoaders.loadNextAd (RewardedAdsLoaders.java:60)
com.mopub.mobileads.MoPubRewardedVideoManager.fetchAd (MoPubRewardedVideoManager.java:321)
com.mopub.mobileads.MoPubRewardedVideoManager.loadVideo (MoPubRewardedVideoManager.java:308)
com.mopub.mobileads.MoPubRewardedVideoManager.failover (MoPubRewardedVideoManager.java:634)
com.mopub.mobileads.MoPubRewardedVideoManager.onAdError (MoPubRewardedVideoManager.java:590)
com.mopub.mobileads.RewardedAdsLoaders$RewardedVideoRequestListener.onErrorResponse (RewardedAdsLoaders.java:40)
com.mopub.network.AdLoader.deliverError (AdLoader.java:300)
com.mopub.network.AdLoader.access$200 (AdLoader.java:35)
com.mopub.network.AdLoader$3.run (AdLoader.java:170)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:210)
com.unity3d.player.UnityPlayer$e.run (未知来源:32)

#### Evidence:
Device log files, Network log file, etc.

**Comment by p158276** [comment]
Hi @circularity, Thanks for reaching out!
Could you help me to fill the following forum so that we'll get a better understanding of the issues?

------------

One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

#### Android Studio Version:

#### Gradle Version:

#### Device model and OS Version:

#### Ad Unit IDs used in reproducing the issue:

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

------------

And seems like the exception happens intentionally.
https://github.com/mopub/mopub-android-sdk/blob/dfd5633950314041c57dbecc21e30a037075af2d/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/common/Preconditions.java#L248
Can you also provide the error message? 

Thank you.

Yoyo Lin
MoPub Team

**Comment by circularity** [comment]
> Hi @circularity, Thanks for reaching out!
> Could you help me to fill the following forum so that we'll get a better understanding of the issues?
> 
> One line summary of the issue here
> 
> * [ ]  I am submitting a bug report for existing functionality
> * [ ]  I visited https://developers.mopub.com/ and found no answer
> * [ ]  I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
> * [ ]  I checked to make sure that this issue has not already been filed
> 
> #### MoPub SDK Version:
> #### Android Studio Version:
> #### Gradle Version:
> #### Device model and OS Version:
> #### Ad Unit IDs used in reproducing the issue:
> #### Steps to reproduce the behavior:
> Please list all relevant steps to reproduce the observed behavior.
> 
> #### Expected behavior:
> As concisely as possible, describe the expected behavior.
> 
> #### Observed behavior:
> As concisely as possible, describe the observed behavior.
> 
> #### Evidence:
> Device log files, Network log file, etc.
> 
> And seems like the exception happens intentionally.
> https://github.com/mopub/mopub-android-sdk/blob/dfd5633950314041c57dbecc21e30a037075af2d/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/common/Preconditions.java#L248
> 
> 
> Can you also provide the error message?
> Thank you.
> 
> Yoyo Lin
> MoPub Team

thanks 

this form firebase crashlytics

Fatal Exception: java.lang.Error: FATAL EXCEPTION [UnityMain]
Unity version     : 2018.2.11f1
Device model      : samsung SM-S102DL
Device fingerprint: samsung/a10etfn/a10e:9/PPR1.180610.011/S102DLUDS2ASJ1:user/release-keys

**Comment by p158276** [comment]
Hi @circularity,
Can you provide the ad format you are currently using and the ad unit id?

Thank you.

Yoyo Lin
MoPub Team

**Comment by chauduyphanvu** [comment]
@circularity, are you able to provide the information above? 

Vu Chau
MoPub Tea,
