### ISSUE TITLE
Adapters require activity context

### ISSUE THREAD

**Issue by CatKaiserGIT** [mopub/mopub-android-sdk#395]
Ad networks adapters require an activity context, but adapters are initialised with application context.

For example ChartboostAdapterConfiguration for Chartboost ad network requires an activity context, though AdapterConfigurationManager takes application context:

```
public void initialize(@NonNull final Context context,
            @NonNull final Set<String> adapterConfigurationClasses,
            @NonNull final Map<String, Map<String, String>> networkMediationConfigurations,
            @NonNull final Map<String, Map<String, String>> moPubRequestOptions) {
        Preconditions.checkNotNull(context);
        Preconditions.checkNotNull(adapterConfigurationClasses);
        Preconditions.checkNotNull(networkMediationConfigurations);
        Preconditions.checkNotNull(moPubRequestOptions);

        AsyncTasks.safeExecuteOnExecutor(
                new AdapterConfigurationsInitializationAsyncTask(context.getApplicationContext(),
                        adapterConfigurationClasses, networkMediationConfigurations,
                        moPubRequestOptions, this));
    }
```

#### MoPub SDK Version:
5.12.0
#### Chartboost Adapter Version:
7.5.0.3
#### Android Studio Version:
3.6.2
#### Gradle Version:
5.6.4

**Comment by chauduyphanvu** [comment]
@CatKaiserGIT, thanks for getting in touch! This is an expected behavior:

* Initialization of the MoPub SDK uses an Activity Context for rewarded video initialization
* Initialization of mediated network SDKs is passed an `Application` Context by default

For networks that cannot initialize as a result, you have the option of initializing them directly from your app using appropriate arguments that their APIs require. Otherwise, network SDKs have a chance to do a lazy initialization at the time of the ad request. For example, ironSource can initialize its SDK [here](https://github.com/mopub/mopub-android-mediation/blob/778cd4a4839b248a1f03e519d542ba4b3801b219/IronSource/src/main/java/com/mopub/mobileads/IronSourceInterstitial.java#L109) because the `Context` passed to `IronSourceInterstitial.loadInterstitial()` is an [Activity Context](https://github.com/mopub/mopub-android-sdk/blob/dc46332d8fdf6c4ed99d588dd6776821b671a652/mopub-sdk/mopub-sdk-interstitial/src/main/java/com/mopub/mobileads/CustomEventInterstitialAdapter.java#L54), which ironSource needs to initialize.

Let us know if you have any questions!

Vu Chau
MoPub Team

**Comment by CatKaiserGIT** [comment]
@chauduyphanvu , why does MoPub sdk complains about it then during initialization? Shouldn't it be complaining only when we are actually using interstitials as you pointed out for IronSource? I think that this is very misleading.

**Comment by chauduyphanvu** [comment]
Thanks for the feedback. I took a look, and we have a [new Chartboost adapter](https://github.com/mopub/mopub-android-mediation/blob/master/Chartboost/CHANGELOG.md) that no longer needs an Activity Context, so if you upgrade to v8.0.1.0+ of the adapter, this should no longer be an issue.

Back to the logs, I understand your confusion and we will be working on cleaning logging messages so they are clearer. You also have the option to [disable verbose logging](https://developers.mopub.com/publishers/android/test/#enable-logging). In the meantime, there are no fatal problems if network SDKs do not get to initialize, because they will initialize later prior to the ad request. For other network SDKs that have specific initialization requirements, we are actively working with them to find a common resolution.

**Comment by CatKaiserGIT** [comment]
Thank you very much for your swift response and support! Will check out new
adapters.
