### ISSUE TITLE
Request to drop the minimum Android SDK version to API level 16

### ISSUE THREAD

**Issue by JulianEggers** [mopub/mopub-android-sdk#396]
In Version 5.11.0 you raise the minimum Android SDK to Android 4.4 (API level 19).

I would like to understand why this was done and whether this can be changed in future to support older API levels again.

In my specific case, I would like to use the latest MoPub SDK and still be able to use it for phones running on API level 16. 
It is just 2% of all android phones that are not supported anymore but it is still 2% more income and should not be left out.

#### MoPub SDK Version:
5.11.0

**Comment by chauduyphanvu** [comment]
@JulianEggers, thanks for getting in touch about the min API level. 

We made that decision after taking several things into consideration. For one, moving to API level 19 simplified a lot of our code that handled fallback switches due to Android APIs that don't reliably run ob versions before 19. Additionally, several mediation network SDKs we partner with already required 19 so publishers likely needed 19 or above to use mediation.

Having 19 as the min also allows us to move quicker to support new tech stacks (AndroidX VideoView, ExoPlayer, WebView JS debugging, etc.) and dramatically improve the performance of the SDK. Since little traffic is generated from older Android versions, and it’s slowing down our work, it is not worth maintaining this backwards compatibility.

Let us know if you have additional concerns.
Vu Chau
MoPub Team
