### ISSUE TITLE
Audio focus is occupied by interstitial ad

### ISSUE THREAD

**Issue by JoyHong** [mopub/mopub-android-sdk#419]
Hey, guys

I seems find an new issue that when i'm listening music, and then load MoPub interstitial ad, my music will pause, and cannot resume what ever i destroy the ad or close the ad.

please help to have a check thanks.

#### MoPub SDK Version: 5.13.1

**Comment by p158276** [comment]
Hi @JoyHong ,
Thanks for reaching out.
Please share the following information so we can target the problem efficiently. 
Besides, do you happen to know which network shows this problem?

-------
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:

#### Android Studio Version:

#### Gradle Version:

#### Device model and OS Version:

#### Ad Unit IDs used in reproducing the issue:

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

------ 

Yoyo Lin
MoPub Team
