### ISSUE TITLE
Sample app does not compile due to Mintegral

### ISSUE THREAD

**Issue by npace** [mopub/mopub-android-sdk#431]
I tried cloning the repo to build the sample app, but gradle sync failed because of the Mintegral integration.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.13.1, compiled from the `v5.13.1` release tag.

#### Android Studio Version:
4.0.1

#### Gradle Version:
5.6.4

#### Device model and OS Version:
Samsung SM-A405FN, Android 10, API 29

#### Ad Unit IDs used in reproducing the issue:
N/A

#### Steps to reproduce the behavior:
Just try to gradle sync the project

#### Expected behavior:
Project should compile

#### Observed behavior:
Project does not compile

#### Evidence:
N/A

**Comment by chauduyphanvu** [comment]
@npace, this isn't an issue with the MoPub SDK or sample app per se, as Mintegral is no longer a supported ad network per https://developers.mopub.com/publishers/mediation/mopub-network-mediation/#deprecated-networks. 

Adapters have been taken down, which is why you ran into an issue using our sample app. Please manually remove the adapter entry from Gradle. We will be doing the same for the next SDK + sample app release.

Vu Chau
MoPub Team
