### ISSUE TITLE
CustomEventBanner not found after updating Mopub version from 5.12.x to to 5.13.x

### ISSUE THREAD

**Issue by Smbat888** [mopub/mopub-android-sdk#441]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.

**Comment by chauduyphanvu** [comment]
@Smbat888, you need the 5.13.0+ compatible mediation adapters now because there were API-breaking changes in this MoPub SDK version. Check the [changelogs](https://github.com/mopub/mopub-android-mediation) for the ad networks you are integrating in order to know the minimum adapter versions you must integrate.

Vu Chau
MoPub Team
