### ISSUE TITLE
Some Network requires Activity Context instead of Application Context

### ISSUE THREAD

**Issue by firatagdas** [mopub/mopub-android-sdk#454]
https://github.com/mopub/mopub-android-sdk/blob/51030ebbbc375debd114ec869b5a1a6902b3dafa/mopub-sdk/mopub-sdk-base/src/main/java/com/mopub/common/AdapterConfigurationManager.java#L58

Some networks requires Activity Context instead of Application Context. It was the case before Chartboost <8.0.1. Some custom networks implemented by us also requires Activity context via Adapter Configuration. Can you please switch this to only context?

**Comment by hmertkahraman** [comment]
Hi @firatagdas ,

Thanks for reaching out with this feedback. We will look into this and get back to you.

MoPub Team

**Comment by firatagdas** [comment]
Hello, an update on this: 

Ironsource requires Activity context on its final version: https://github.com/mopub/mopub-android-mediation/blob/master/IronSource/src/main/java/com/mopub/mobileads/IronSourceAdapterConfiguration.java#L91

**Comment by wacamoe** [comment]
Hi @firatagdas - you are correct, some networks use Activity and some use Context. Therefore we currently use Activity because certain networks require this. We are constantly trying to unify across the platform and are always in active discussions with our network partners. Should there be any more movement in this regard, we will update the code accordingly.

Thank you for your concern!
