### ISSUE TITLE
Cannot Set clickable areas for  Facebook native ad by myself

### ISSUE THREAD

**Issue by williamycyh** [mopub/mopub-android-sdk#481]
Cannot Set clickable areas  for Facebook native ad by myself
For example, like the official Facebook implementation:
// Create a list of clickable views
    List<View> clickableViews = new ArrayList<>();
    clickableViews.add(nativeAdTitle);
    clickableViews.add(nativeAdCallToAction);

    // Register the Title and CTA button to listen for clicks.
    nativeAd.registerViewForInteraction(
            adView, nativeAdMedia, nativeAdIcon, clickableViews);

We can control which areas can be clicked to optimize advertising effects.

**Comment by chauduyphanvu** [comment]
@williamycyh, since you are requesting ads from an ad network via [MoPub's mediation system](https://developers.mopub.com/publishers/mediation/mopub-network-mediation/), certain features supported by the ad network might not be supported from MoPub's perspective, including specifying clickable areas by yourself in this case. This is because not all features are externally exposed via an API.

See [this code](https://github.com/mopub/mopub-android-mediation/blob/master/FacebookAudienceNetwork/src/main/java/com/mopub/nativeads/FacebookNative.java#L137-L154) for the current clickable areas that MoPub and Facebook have agreed upon: 

```java
        final List<View> clickableViews = new ArrayList<>();
        assembleChildViewsWithLimit(view, clickableViews, 10);

        if (nativeAdBase instanceof NativeAd && mediaView != null) {
            NativeAd nativeAd = (NativeAd) nativeAdBase;
            if (clickableViews.size() == 1) {
                nativeAd.registerViewForInteraction(view, mediaView, adIconView);
            } else {
                nativeAd.registerViewForInteraction(view, mediaView, adIconView, clickableViews);
            }
        } else if (nativeAdBase instanceof NativeBannerAd) {
            NativeBannerAd nativeBannerAd = (NativeBannerAd) nativeAdBase;
            if (clickableViews.size() == 1) {
                nativeBannerAd.registerViewForInteraction(view, adIconView);
            } else {
                nativeBannerAd.registerViewForInteraction(view, adIconView, clickableViews);
            }
        }
```

Vu Chau
MoPub Team
